### ISSUE TITLE
Missing embedding file

### ISSUE THREAD

**Issue by Arjunsankarlal** [wuzhen247/HUAPA#1]
While starting the training, the embedding file for the dataset is required. It has to be generated by ourselves? If so can you provide us the link to the dataset?

**Comment by wuzhen247** [comment]
It is not allowed to upload big file more than 100M to the github. So I upload the embedding file to Baidu Netdisk, the link is https://pan.baidu.com/s/195jduYugfYIgZLbHXHmKaA#list/path=%2F. Of course, you can also generate them by yourself. Thanks for your advice, I will update README and provide the link.
