### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by 01abc** [wuzhen247/HUAPA#11]
user_num和user_id是一样的吗？

**Comment by wuzhen247** [comment]
> user_num和user_id是一样的吗？

不同，user_num是用户总数目，user_id是每个用户的id

**Comment by 01abc** [comment]
您好！我还想问一下，IMDB和Yelp的极性划分的中间分是多少呢？就是比如IMDB一共5分，多少分以上是积极的呢？以及Yelp？谢谢！

**Comment by wuzhen247** [comment]
> 您好！我还想问一下，IMDB和Yelp的极性划分的中间分是多少呢？就是比如IMDB一共5分，多少分以上是积极的呢？以及Yelp？谢谢！

可以根据自己的需求定义，比如对于IMDB，你可以把rating 3视为neutral，4、5为positive，1、2为negative
