### ISSUE TITLE
I need some help about dataset

### ISSUE THREAD

**Issue by 01abc** [wuzhen247/HUAPA#12]
您好！我想请问下dataset里面都是ss文件，我想问下这个可以转换成txt文件吗？或者这个ss文件应该怎么用呢？

**Comment by wuzhen247** [comment]
> 您好！我想请问下dataset里面都是ss文件，我想问下这个可以转换成txt文件吗？或者这个ss文件应该怎么用呢？

重命名为.txt应该就可以了
