### ISSUE TITLE
The models on both sides are the same, and the training labels are the same. How can we say that one side focuses on the user side and the other side focuses on the product side.

### ISSUE THREAD

**Issue by Linjz1** [wuzhen247/HUAPA#14]

**Comment by wuzhen247** [comment]
The user id and product id for attention are different, and they are also the input.

**Comment by wuzhen247** [comment]
> _No description provided._

The user id and product id for attention are different, and they are also the input.

**Comment by Linjz1** [comment]
thank you @wuzhen247
