### ISSUE TITLE
I can not download embedding file

### ISSUE THREAD

**Issue by MahdiHeybati** [wuzhen247/HUAPA#4]
Hi 
I can not download embedding files 
could you please send me this files ?

**Comment by wuzhen247** [comment]
Yeah, for convenience, I have uploaded the embedding files to Google Drive. You can download them from https://drive.google.com/drive/folders/19r6Bj-s0intWCSIdd1W3dqOPueAc_K2N

**Comment by wuzhen247** [comment]
> Hi
> I can not download embedding files
> could you please send me this files ?
Yeah, for convenience, I have uploaded the embedding files to Google Drive. You can download them from https://drive.google.com/drive/folders/19r6Bj-s0intWCSIdd1W3dqOPueAc_K2N

**Comment by wuzhen247** [comment]
> Hi
> I can not download embedding files
> could you please send me this files ?

Yeah, for convenience, I have uploaded the embedding files to Google Drive. You can download them from https://drive.google.com/drive/folders/19r6Bj-s0intWCSIdd1W3dqOPueAc_K2N

**Comment by chaiguanpeng** [comment]
how i to use embedding files

**Comment by wuzhen247** [comment]
> how i to use embedding files

Put the embedding file into the folder of the corresponding dataset.
