### ISSUE TITLE
请问您得到论文中的结果所使用的超参数配置？

### ISSUE THREAD

**Issue by SleepyBag** [wuzhen247/HUAPA#5]
我正在尝试运行您的代码来复现您论文中的成果。我检查过之后发现代码中的默认参数与您论文中所提到的配置是一样的。
但是跑了两次之后我发现这个代码的默认参数在IMDB数据集上只能跑到0.540左右的成绩（每次大概跑25000个step）。我想知道的是：

1.代码中是否有什么地方的配置是论文中没有提到的，还需要去调的吗？
2.如果有，可否提供一下这些参数的配置？

**Comment by wuzhen247** [comment]
你好，按照目前的参数设置，25000个step在IMDB上差不多30个epochs。因为IMDB数据集较大，根据之前的经验，模型在超过100个epochs之后会有一些更好的结果，因此不建议在几十个epochs的地方stop。

**Comment by wuzhen247** [comment]
> 我正在尝试运行您的代码来复现您论文中的成果。我检查过之后发现代码中的默认参数与您论文中所提到的配置是一样的。
> 但是跑了两次之后我发现这个代码的默认参数在IMDB数据集上只能跑到0.540左右的成绩（每次大概跑25000个step）。我想知道的是：
> 
> 1.代码中是否有什么地方的配置是论文中没有提到的，还需要去调的吗？
> 2.如果有，可否提供一下这些参数的配置？

你好，按照目前的参数设置，25000个step在IMDB上差不多30个epochs。因为IMDB数据集较大，根据之前的经验，模型在超过100个epochs之后会有一些更好的结果，因此不建议在几十个epochs的地方stop。

**Comment by SleepyBag** [comment]
好的，谢谢～
